### ISSUE TITLE
source code release?

### ISSUE THREAD

**Issue by roptat** [plume-lib/plume-util#3]
Hi, I'd like to package plume-util in my distro as a dependency of other things. I'm currently using commit db6dd1795b942e75360bf93de16f973922d767d8 as version 1.0.5, but it'd be so much nicer if you had a source release somewhere. Can you do that? I think all you need to do is add a tag to the corresponding commit in git and github should automatically create a release for you.

Thank you!

**Comment by mernst** [comment]
I have added tags to reflection-util and to plume-util.  I made a reflection-util release on GitHub, and I will do so for plume-util in the future.  (But for now, plume-util just has a [`v1.0.5` tag](https://github.com/plume-lib/plume-util/tree/v1.0.5).

I'm glad you find the packages useful, and I hope they are now more so.
